# Generated by Django 2.0.6 on 2018-10-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('currentBal', models.IntegerField()),
                ('emergency', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
