# Generated by Django 2.0.6 on 2018-10-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currentBal',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency',
            field=models.CharField(max_length=6),
        ),
    ]
